[package]
name = "evangelism"
version = "0.1.0"
authors = ["Valery Litvin <litvintech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = ["cranelift"]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = [ "cosmwasm/backtraces", "cosmwasm-vm/backtraces" ]
cranelift = [ "cosmwasm-vm/default-cranelift"]
singlepass = [ "cosmwasm-vm/default-singlepass"]

[dependencies]
cosmwasm = { version = "0.6.3" }
cw-storage = "0.1.1"
named_type = "=0.2.1"
named_type_derive = "=0.2.1"
schemars = "=0.5"
serde = { version = "=1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "=0.5.0", default-features = false, features = ["rust_1_30"] }
# needed for wasm-pack build process
wasm-bindgen = "=0.2.55"

[dev-dependencies]
cosmwasm-vm = { version = "0.6.3", default-features = false }
serde_json = "1.0"
